version: "3"
services:
    backend:
        image: backend
        ports:
            - "9999:9999"
        restart: unless-stopped
        env_file:
            - .env
        networks:
            - network

    bot:
        image: bot_container
        networks:
            - network
networks:
    network:
        ipam:
            driver: default
            config:
                - subnet: 172.18.1.0/24
