version: "3"
services:
    database:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - db_data:/var/lib/postgresql/data
        env_file:
            - .env
        networks:
            - network
    backend:
        depends_on:
            - database
            - redis
        image: backend
        ports:
            - "8080:8000"
        restart: unless-stopped
        env_file:
            - .env
        networks:
            - network
    redis:
        image: redis
        ports:
            - "6379:6379"
        networks:
            - network

volumes:
    db_data:

networks:
    network:
        ipam:
            driver: default
            config:
                - subnet: 172.18.1.0/24